
#### 整合freemarker
spring:
    freemarker:
        cache: false
        charset: UTF-8
        check-template-location: true
        content-type: text/html
        expose-request-attributes: true
        expose-session-attributes: true
        request-context-attribute: request
        suffix: .ftl
        template-loader-path:
        - classpath:/templates/
    application:
        name: app-shop-portal-web
###服务注册到eureka地址
eureka:
  client:
    service-url:
           defaultZone: http://111.229.41.20:8100/eureka
  server:
      # 测试时关闭自我保护机制，保证不可用服务及时踢出
      enable-self-preservation: false
      eviction-interval-timer-in-ms: 2000

server:
    port: 80
ribbon:
    ReadTimeout: 60000
    ConnectTimeout: 60000
