###服务启动端口号
server:
  port: 8300
###服务名称(服务注册到eureka名称)
spring:
  application:
    name: app-mayikt-member
##  redis
  redis:
    host: 111.229.41.20
    port: 6379
    password: 123456
### 数据库相关连接
  datasource:
    username: pig
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://111.229.41.20:3306/shop-member?useUnicode=true&characterEncoding=utf-8&useSSL=false

###服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://111.229.41.20:8100/eureka


###swagger相关配置
swagger:
  base-package: com.member.service
  title: 会员服务接口
  description: 会员服务
  version: 1.1
  terms-of-service-url: www.mayikt.com

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
####打印MyBatias日志
logging:
  level:
    ### 开发环境使用DEBUG 生产环境info或者error
    com.mayikt.member.mapper: DEBUG
