###服务启动端口号
server:
  port: 8200
###服务名称(服务注册到eureka名称)
spring:
  application:
    name: app-mayikt-weixin
###服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka
swagger:
  base-package: weixinServiceImpl.serviceImpl
  title: SpringCloud2.x构建微服务电商项目-微信服务接口
  description: 微信服务
  version: 1.1
  terms-of-service-url: www.mayikt.com
